#!/bin/bash
# Media Stack Setup Helper
# Creates required folders, prepares the .env file, and migrates config to local disk.
# Usage: bash scripts/setup.sh [--media-dir DIR] [--config-dir DIR] [--pia] [--help]

set -euo pipefail

YELLOW='\033[1;33m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
NC='\033[0m'

usage() {
    cat <<EOF
Usage: bash scripts/setup.sh [OPTIONS]

Creates Media folders, local app config folders, and generates .env from .env.example.

Options:
  --media-dir DIR    Media root path (default: from .env, otherwise ~/Media)
  --config-dir DIR   Local app config path (default: from .env, otherwise ~/home-media-stack/config)
  --pia              Configure .env for PIA (OpenVPN) instead of ProtonVPN
  --help             Show this help message
EOF
}

read_env_key_from_file() {
    local key="$1"
    local env_file="$2"
    if [[ ! -f "$env_file" ]]; then
        return 0
    fi
    sed -n "s/^${key}=//p" "$env_file" | head -1
}

strip_wrapping_quotes() {
    local value="$1"
    value="${value%\"}"
    value="${value#\"}"
    value="${value%\'}"
    value="${value#\'}"
    printf '%s\n' "$value"
}

set_env_key() {
    local key="$1"
    local value="$2"
    local escaped_value="${value//&/\\&}"
    escaped_value="${escaped_value//|/\\|}"
    if grep -q "^${key}=" "$ENV_FILE"; then
        sed -i '' "s|^${key}=.*|${key}=${escaped_value}|" "$ENV_FILE"
    else
        echo "${key}=${value}" >> "$ENV_FILE"
    fi
}

get_env_key() {
    local key="$1"
    sed -n "s/^${key}=//p" "$ENV_FILE" | head -1
}

migrate_legacy_configs() {
    local legacy_config_dir="$MEDIA_DIR/config"
    local service src dst
    local -a services=(qbittorrent prowlarr sonarr radarr bazarr seerr jellyfin)

    if [[ ! -d "$legacy_config_dir" ]]; then
        return 0
    fi

    echo -e "${CYAN}Migrating legacy config folders from $legacy_config_dir (non-destructive)...${NC}"
    for service in "${services[@]}"; do
        src="$legacy_config_dir/$service"
        dst="$CONFIG_DIR/$service"

        if [[ ! -d "$src" ]]; then
            echo "  - $service: not-found"
            continue
        fi

        if find "$dst" -mindepth 1 -print -quit | grep -q .; then
            echo "  - $service: skipped-existing"
            continue
        fi

        cp -a "$src/." "$dst/"
        echo "  - $service: copied"
    done
    echo ""
}

generate_local_runbook() {
    local runbook_root runbook_file generated_at creds_file
    runbook_root="$HOME/home-media-stack"
    runbook_file="$runbook_root/README.md"
    generated_at="$(date '+%Y-%m-%d %H:%M:%S %Z')"
    creds_file="$MEDIA_DIR/state/first-run-credentials.txt"

    mkdir -p "$runbook_root"

    cat > "$runbook_file" <<EOF
# Home Media Stack Local Runbook

_Last generated by \`scripts/setup.sh\`: ${generated_at}_

## Paths
- Install directory: $SCRIPT_DIR
- Media directory: $MEDIA_DIR
- Local app config directory: $CONFIG_DIR
- Credentials file: $creds_file

## Expected Media Folders
- $MEDIA_DIR/Movies
- $MEDIA_DIR/TV Shows
- $MEDIA_DIR/Downloads

## Expected App Config Folders
- $CONFIG_DIR/qbittorrent
- $CONFIG_DIR/prowlarr
- $CONFIG_DIR/sonarr
- $CONFIG_DIR/radarr
- $CONFIG_DIR/bazarr
- $CONFIG_DIR/seerr
- $CONFIG_DIR/jellyfin

## Service URLs
- Seerr: http://localhost:5055
- qBittorrent: http://localhost:8080
- Prowlarr: http://localhost:9696
- Sonarr: http://localhost:8989
- Radarr: http://localhost:7878
- Bazarr: http://localhost:6767
- Jellyfin (if enabled): http://localhost:8096
- Plex (native app): http://localhost:32400/web

## Useful Commands
\`\`\`bash
cd "$SCRIPT_DIR"
docker compose ps
docker compose logs --tail 100 gluetun qbittorrent radarr sonarr seerr
bash scripts/doctor.sh --media-dir "$MEDIA_DIR" --config-dir "$CONFIG_DIR"
bash scripts/health-check.sh
bash scripts/configure.sh
\`\`\`

## VPN Egress Check (qBittorrent via Gluetun)
\`\`\`bash
cd "$SCRIPT_DIR"
docker compose exec -T gluetun sh -lc 'wget -qO- https://ipinfo.io/ip'
docker compose exec -T qbittorrent sh -lc 'wget -qO- https://ipinfo.io/ip'
\`\`\`

## Known Failure Signals
- \`database is locked\` in Radarr/Sonarr logs usually means app databases are on SMB/NFS. Keep \`CONFIG_DIR\` on local disk.
- Repeated Gluetun auth/connect errors usually indicate VPN credentials in \`.env\` are missing or invalid.
- Seerr request failures with Radarr/Sonarr 4xx/5xx are usually upstream API/config errors; check Arr logs first.
EOF
}

MEDIA_DIR_OVERRIDE=""
CONFIG_DIR_OVERRIDE=""
VPN_PROVIDER_OVERRIDE=""
while [[ $# -gt 0 ]]; do
    case "$1" in
        --media-dir)
            if [[ $# -lt 2 || "$2" == --* ]]; then
                echo "Missing value for --media-dir"
                usage
                exit 1
            fi
            MEDIA_DIR_OVERRIDE="$2"
            shift 2
            ;;
        --config-dir)
            if [[ $# -lt 2 || "$2" == --* ]]; then
                echo "Missing value for --config-dir"
                usage
                exit 1
            fi
            CONFIG_DIR_OVERRIDE="$2"
            shift 2
            ;;
        --pia)
            VPN_PROVIDER_OVERRIDE="pia"
            shift
            ;;
        --help|-h)
            usage
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            usage
            exit 1
            ;;
    esac
done

SCRIPT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"

echo ""
echo "=============================="
echo "  Media Stack Setup"
echo "=============================="
echo ""

# Detect current user and home directory
CURRENT_USER=$(whoami)
HOME_DIR=$(eval echo ~$CURRENT_USER)

DEFAULT_MEDIA_DIR="$HOME_DIR/Media"
DEFAULT_CONFIG_DIR="$HOME_DIR/home-media-stack/config"

if [[ -n "$MEDIA_DIR_OVERRIDE" ]]; then
    MEDIA_DIR="$MEDIA_DIR_OVERRIDE"
else
    MEDIA_DIR="$(read_env_key_from_file "MEDIA_DIR" "$ENV_FILE")"
fi

if [[ -n "$CONFIG_DIR_OVERRIDE" ]]; then
    CONFIG_DIR="$CONFIG_DIR_OVERRIDE"
else
    CONFIG_DIR="$(read_env_key_from_file "CONFIG_DIR" "$ENV_FILE")"
fi

MEDIA_DIR="$(strip_wrapping_quotes "${MEDIA_DIR:-$DEFAULT_MEDIA_DIR}")"
CONFIG_DIR="$(strip_wrapping_quotes "${CONFIG_DIR:-$DEFAULT_CONFIG_DIR}")"
MEDIA_DIR="${MEDIA_DIR/#\~/$HOME}"
CONFIG_DIR="${CONFIG_DIR/#\~/$HOME}"

echo "Detected user: $CURRENT_USER"
echo "Media folder will be:  $MEDIA_DIR"
echo "Config folder will be: $CONFIG_DIR"
echo ""

# Get user ID
USER_PUID=$(id -u)
USER_PGID=$(id -g)

# Create folder structure
echo "Creating folders..."
mkdir -p "$MEDIA_DIR"/{Downloads,Movies,"TV Shows",logs,state}
mkdir -p "$MEDIA_DIR"/Downloads/complete/{radarr,tv-sonarr}
mkdir -p "$CONFIG_DIR"
mkdir -p "$CONFIG_DIR"/{qbittorrent,prowlarr,sonarr,radarr,bazarr,seerr,jellyfin}
echo -e "  ${GREEN}Done${NC}"
echo ""

# Create .env from example if it doesn't exist
if [[ -f "$ENV_FILE" ]]; then
    echo -e "${YELLOW}Note:${NC} .env already exists. Skipping creation."
    echo "  Existing values are preserved unless setup needs to normalize keys."
else
    echo "Creating .env file..."
    sed "s|/Users/YOURUSERNAME/Media|$MEDIA_DIR|g" "$SCRIPT_DIR/.env.example" \
        | sed "s|/Users/YOURUSERNAME/home-media-stack/config|$CONFIG_DIR|g" \
        | sed "s|PUID=501|PUID=$USER_PUID|g" \
        | sed "s|PGID=20|PGID=$USER_PGID|g" \
        > "$ENV_FILE"
    chmod 600 "$ENV_FILE"
    echo -e "  ${GREEN}Done${NC}"
    echo ""
fi

# Keep existing .env in sync with any newly added keys from .env.example.
added_keys=()
while IFS= read -r line; do
    [[ "$line" =~ ^[A-Za-z_][A-Za-z0-9_]*= ]] || continue
    key="${line%%=*}"
    if ! grep -q "^${key}=" "$ENV_FILE"; then
        echo "$line" >> "$ENV_FILE"
        added_keys+=("$key")
    fi
done < "$SCRIPT_DIR/.env.example"

if [[ "${#added_keys[@]}" -gt 0 ]]; then
    echo -e "${YELLOW}Note:${NC} Added missing .env keys from .env.example:"
    for key in "${added_keys[@]}"; do
        echo "  - $key"
    done
    echo ""
fi

# Normalize paths every run so compose/scripts stay in sync with resolved values.
set_env_key "MEDIA_DIR" "$MEDIA_DIR"
set_env_key "CONFIG_DIR" "$CONFIG_DIR"

migrate_legacy_configs

if [[ "$VPN_PROVIDER_OVERRIDE" == "pia" ]]; then
    set_env_key "VPN_PROVIDER" "pia"
    set_env_key "VPN_SERVICE_PROVIDER" "private internet access"
    set_env_key "VPN_TYPE" "openvpn"
    set_env_key "SERVER_COUNTRIES" ""
    set_env_key "SERVER_REGIONS" ""
    set_env_key "VPN_PORT_FORWARDING_PROVIDER" ""
    # Gluetun parses WireGuard addresses even when using OpenVPN.
    # Clear placeholders to prevent parse errors on startup.
    set_env_key "WIREGUARD_PRIVATE_KEY" ""
    set_env_key "WIREGUARD_ADDRESSES" ""
else
    # If provider is already set to PIA, normalize obvious Proton defaults
    # that may have been added from .env.example during sync.
    current_vpn_provider="$(get_env_key "VPN_PROVIDER")"
    if [[ "$current_vpn_provider" == "pia" ]]; then
        vpn_service_provider="$(get_env_key "VPN_SERVICE_PROVIDER")"
        vpn_type="$(get_env_key "VPN_TYPE")"
        server_countries="$(get_env_key "SERVER_COUNTRIES")"
        vpn_pf_provider="$(get_env_key "VPN_PORT_FORWARDING_PROVIDER")"
        wg_private_key="$(get_env_key "WIREGUARD_PRIVATE_KEY")"
        wg_addresses="$(get_env_key "WIREGUARD_ADDRESSES")"

        if [[ -z "$vpn_service_provider" || "$vpn_service_provider" == "protonvpn" ]]; then
            set_env_key "VPN_SERVICE_PROVIDER" "private internet access"
        fi
        if [[ -z "$vpn_type" || "$vpn_type" == "wireguard" ]]; then
            set_env_key "VPN_TYPE" "openvpn"
        fi
        if [[ "$server_countries" == "United States" ]]; then
            set_env_key "SERVER_COUNTRIES" ""
        fi
        # Leave SERVER_REGIONS empty by default for PIA so the port-forward-only
        # filter can match any valid region.
        if [[ "$vpn_pf_provider" == "protonvpn" ]]; then
            set_env_key "VPN_PORT_FORWARDING_PROVIDER" ""
        fi
        if [[ "$wg_private_key" == "your_wireguard_private_key_here" ]]; then
            set_env_key "WIREGUARD_PRIVATE_KEY" ""
        fi
        if [[ "$wg_addresses" == "your_wireguard_address_here" ]]; then
            set_env_key "WIREGUARD_ADDRESSES" ""
        fi
    fi
fi

generate_local_runbook
echo -e "  ${GREEN}Runbook updated:${NC} $HOME/home-media-stack/README.md"
echo ""

# Read VPN_PROVIDER from .env for setup messaging.
vpn_provider="$(sed -n 's/^VPN_PROVIDER=//p' "$ENV_FILE" | head -1)"
vpn_provider="${vpn_provider:-protonvpn}"
echo -e "${YELLOW}IMPORTANT:${NC} You still need to add your VPN credentials to .env"
echo "  Open .env in a text editor and fill in:"
if [[ "$vpn_provider" == "pia" ]]; then
    echo "    - OPENVPN_USER and OPENVPN_PASSWORD (from your PIA account)"
else
    echo "    - WIREGUARD_PRIVATE_KEY and WIREGUARD_ADDRESSES (from your ProtonVPN account)"
fi

echo ""
echo "=============================="
echo "  Setup complete!"
echo "=============================="
echo ""
echo "Next steps:"
echo "  1. Add VPN credentials to .env (if not already done)"
echo "  2. Run: docker compose up -d"
echo "     (or: docker compose --profile jellyfin up -d if MEDIA_SERVER=jellyfin)"
echo "  3. Run: bash scripts/health-check.sh"
echo "  4. Follow the rest of SETUP.md for Plex + app configuration"
echo ""
